//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Infrastructure.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RC {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RC() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Core.Infrastructure.Core.Resources.RC", typeof(RC).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} İşlemi Başarıyla Gerçekleştirildi..
        /// </summary>
        internal static string RC0000 {
            get {
                return ResourceManager.GetString("RC0000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Alanı Boş Bırakılamaz..
        /// </summary>
        internal static string RC0001 {
            get {
                return ResourceManager.GetString("RC0001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İşlem Başarısız Sonuçlandı. İşlem Detayı : {0}.
        /// </summary>
        internal static string RC0002 {
            get {
                return ResourceManager.GetString("RC0002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kayıt Bulunamadı.
        /// </summary>
        internal static string RC0003 {
            get {
                return ResourceManager.GetString("RC0003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yetkisiz İşlem.
        /// </summary>
        internal static string RC0004 {
            get {
                return ResourceManager.GetString("RC0004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erişim Hatası..
        /// </summary>
        internal static string RC0005 {
            get {
                return ResourceManager.GetString("RC0005", resourceCulture);
            }
        }
    }
}
